### ISSUE TITLE
Matomo complains about "File integrity"

### ISSUE THREAD

**Issue by floek** [bitnami/bitnami-docker-matomo#70] opened 2020-12-31 12:51 UTC
**Description**

Matomo complains about `vendor/bin/lessc`:

```
Files were found in your Matomo, but we didn't expect them.
--> Please delete these files to prevent errors. <--

File to delete: vendor/bin/lessc


To delete all these files at once, you can run this command:
rm "/opt/bitnami/matomo/vendor/bin/lessc"
```

**Steps to reproduce the issue:**

1. Open "System Check"

**Describe the results you received:**

Warning:
```
File integrity check failed and reported some errors. You should fix this issue and then refresh this page until it shows no error.
```

**Describe the results you expected:**

No warning

**Comment by Findus23** [comment] 2020-12-31 13:26
Hi,

See also https://github.com/bitnami/bitnami-docker-matomo/issues/68 and https://github.com/matomo-org/matomo-package/pull/124

**Comment by juan131** [comment] 2021-01-04 07:38
Hi @Findus23 

We're still waiting for upstream to fix this issue on their side. Let's close this issue since it's a duplicate of https://github.com/bitnami/bitnami-docker-matomo/issues/68, and reopen the original one until a new version of Matomo is released addressing it.

**Closed by juan131** 2021-01-04 07:38 UTC
