### ISSUE TITLE
Matomo crashed after upgraded 3.12 to 3.11

### ISSUE THREAD

**Issue by Mettmett** [bitnami/bitnami-docker-matomo#44] opened 2019-11-11 15:42 UTC
**Description**
After pulling and composing bitnami/matomo 3.12 from bitnami/matomo 3.11, Matomo application crashed with an error  

**Steps to reproduce the issue:**

1. have a functionnal docker § docker-compose with bitnami/matomo:latest
2. docker-compose pull to have bitnami/matomo:latest (3.12)
3. docker-compose up -d to upgrade the matomo container
4. crash when trying to enter on the web app

**Describe the results you received:**

Error is : 
The following error just broke Matomo (v3.12.0):
Class 'Piwik\DeviceDetectorCache' not found
in /bitnami/matomo/plugins/API/Menu.php line 54

**Describe the results you expected:**

Matomo on 3.12 without pb :) 

**Additional information you deem important (e.g. issue happens only occasionally):**

I'm using bitnami/matomo on a docker-compose file from the hub.docker.com.
I've also tried to remove and create a new container, but same error occur.

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.4
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        9013bf583a
 Built:             Fri Oct 18 15:52:22 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.4
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       9013bf583a
  Built:            Fri Oct 18 15:50:54 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Server:
 Containers: 8
  Running: 8
  Paused: 0
  Stopped: 0
 Images: 7
 Server Version: 19.03.4
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-1062.4.1.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.764GiB
 Name: xxxxxxx
 ID: xxxxxxx
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.24.1, build 4667896b
docker-py version: 3.7.3
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018
```

**Comment by rafariossaa** [comment] 2019-11-12 16:05
Hi @Mettmett ,
  I tried a workaround but it didn't work, so I am creating a internal task to fix this issue.
  We will come back to you as soon as this is fixed.

**Comment by Mettmett** [comment] 2019-11-12 17:02
> Hi @Mettmett ,
> I tried a workaround but it didn't work, so I am creating a internal task to fix this issue.
> We will come back to you as soon as this is fixed.

Thank you for the report ! - I've tried to install manually DeviceDetectorCache but can't go further (same problem), no success ;).

**Comment by makeworld-the-better-one** [comment] 2019-11-26 02:07
Can confirm the issue

**Comment by makeworld-the-better-one** [comment] 2019-11-26 02:19
I am now experiencing the issue below, due to trying out the upgrade and then downgrading again. Is there a way to fix this? I've looked around online and it seems like there's no way to downgrade the SQL database.

![image](https://user-images.githubusercontent.com/25111343/69594104-46ddb700-0fc9-11ea-969f-03ab9ac73500.png)

**Comment by rafariossaa** [comment] 2019-11-26 11:59
Hi,
  Thanks for the confirmation, this task still being in our backlog.
  I didn't found a way to downgrade the database, I think this feature is not supported by Matomo. 
  Maybe asking in Matomo forums can indicate you how to proceed.

**Comment by makeworld-the-better-one** [comment] 2019-11-28 00:07
How can use the [official matomo docker](https://github.com/matomo-org/docker) with the already existing mariadb container that is set up by this repo? That way I could keep my Matomo online and still use the data in my Bitnami mariadb container. Could you outline the configuration steps I would need to use, such as the environment variables I would need to specify when running the official Matomo container?

**Comment by rafariossaa** [comment] 2019-11-28 11:47
Hi,
  I am not familiar that image.
  It seems that you need to set the environment variables for the database connection. You can get those values from the current one.
  Anyways, I would like to suggest to make a database backup beforehand. In this kind of situations anything can happen with the data or configuration in the database, so it is better to be careful.

**Comment by makeworld-the-better-one** [comment] 2019-11-28 13:03
Thanks, I will make a backup. I'm having trouble figuring out which environment variables are needed, the official docker image lists different variables than ones that are in the Dockerfile.

**Comment by rafariossaa** [comment] 2019-11-29 07:27
Please, don't hesitate to share your findings. 
Maybe we can help you in further steps.

Thanks

**Comment by tiferrei** [comment] 2019-11-29 11:40
Hi, we are also encountering this issue.

**Comment by Darkeye9** [comment] 2019-12-18 16:46
I am also experiencing this, please, provide some clues!

**Comment by rafariossaa** [comment] 2019-12-19 09:10
Hi,
  This task still in our backlog.

**Comment by Darkeye9** [comment] 2019-12-19 09:36
Thanks for the response, but could you indicate some workaround in the meanwhile?

Thanks for your time

**Comment by rafariossaa** [comment] 2019-12-19 10:14
No, I am sorry, what I tried didn't work.

**Comment by ShakMR** [comment] 2020-01-09 22:28
Hi everyone,
I am also experiencing this with 3.13.0 when trying to update my docker image. Any update on this?

![Screenshot_2020-01-09 A fatal error occurred](https://user-images.githubusercontent.com/3437307/72110123-bd473600-3337-11ea-8f9c-2d755cfd1a05.png)

**Comment by mattab** [comment] 2020-01-13 01:36
We're getting reports from people who have this issue. 

Do you think Bitnami going to look into this soon? 

If not, we may need to mark the image as not maintained anymore, thanks.

**Comment by beltran-rubo** [comment] 2020-01-13 12:06
Hi all,

We have been investigating the issue. The exact error is the upgrade from version 3.11 to version 3.12, specifically with the plugins/API code.

The Bitnami Matomo container is configured to persist the "plugins/" folder in a separate volume. That way the user can preserve the plugins installed for new updates. The issue is Matomo also ships default plugins that needs to be updated for each version.

@mattab do you think is possible that Matomo ships in one specific folder the default plugins and in a different folder the ones that the user can install after installing it? That way the "default-plugins" folder will not persist and will be up-to-date for every version and the user can save his own plugins in a volume.

**Comment by beltran-rubo** [comment] 2020-01-13 12:17
If the separation of the default plugins and custom plugins is not possible, another possible option is to overwrite the plugins that come by default with Matomo. That way those plugins will be always up-to-date and the user can keep the custom plugins installed in the Volume.

**Comment by mattab** [comment] 2020-01-16 09:14
> do you think is possible that Matomo ships in one specific folder the default plugins and in a different folder the ones that the user can install after installing it? That way the "default-plugins" folder will not persist and will be up-to-date for every version and the user can save his own plugins in a volume.

unfortunately, that's not possible.
However, we would simply recommend to update all folders from /plugins with the latest version from our release of Matomo, and then add back any of your user's other folders (ie. plugins from Marketplace) that is not present in the default release of Matomo. Then it should work without issue?

**Comment by beltran-rubo** [comment] 2020-01-20 08:49
Thanks, we will work on implementing a different approach for this issue.

**Comment by alemorcuq** [comment] 2020-01-23 07:48
Hi, @Mettmett, @makeworld-the-better-one, @tiferrei, @Darkeye9, @ShakMR, @mattab.

We have released two new containers that now replace the persisted default plugins with the ones that come in the deployed zip, making updates possible:

```
3.13.1-debian-9-r5
3.13.1-ol-7-r5
```

Please, have a look and let us know if you find any issues with them.

**Comment by tiferrei** [comment] 2020-01-23 10:31
Thanks @alemorcuq this fixed it!

**Comment by rafariossaa** [comment] 2020-01-24 08:32
Hi @tiferrei,
Thanks for confirming.
I am closing this issue. If you have any other issue, please don't hesitate to report them.

Best regards

**Comment by rafariossaa** [comment] 2020-01-24 09:11
I reopened to wait for confirmation from everyone that reported this issue.

**Comment by Darkeye9** [comment] 2020-01-31 15:16
It worked for me also. Thank you very much!

**Comment by makeworld-the-better-one** [comment] 2020-02-05 23:01
The upgrade worked, but I seemed to have lost all the data in my mariadb container, or I can't access it through the web interface. New data seemed to show up though? I'm not sure if it is just cached or actually going into the database.

Here's what seems to be some relevant log lines from the mariadb container:
```
2020-02-05 22:48:31 42 [Warning] Aborted connection 42 to db: 'bitnami_matomo' user: 'bn_matomo' host: '172.20.0.3' (Got an error reading communication packets)
2020-02-05 22:48:31 37 [Warning] Aborted connection 37 to db: 'bitnami_matomo' user: 'bn_matomo' host: '172.20.0.3' (Got an error reading communication packets)
```
I'm using `bitnami/mariadb:10.3` (`e674a9e2fed8`) and `bitnami/matomo:3.13.1` (`8b17b824c7b8`). Do I need to update mariadb?

Let me know if I should open a new issue.

cc @rafariossaa

**Comment by rafariossaa** [comment] 2020-02-07 07:59
Hi @makeworld-the-better-one ,
  Yes, please, open a new issue.

**Comment by ShakMR** [comment] 2020-02-09 16:39
It worked for me al well. Thanks

**Comment by rafariossaa** [comment] 2020-02-12 08:35
Ok, I am closing this

**Closed by rafariossaa** 2020-02-12 08:35 UTC
