### ISSUE TITLE
How to run behing nginx-proxy

### ISSUE THREAD

**Issue by mebibou** [bitnami/bitnami-docker-matomo#18] opened 2018-05-28 15:04 UTC
I'm trying to run the container behind nginx-proxy to use with Virtual Host. I've started the proxy using the command shown on the official doc:
```
docker run -d -p 80:80 -v /var/run/docker.sock:/tmp/docker.sock:ro jwilder/nginx-proxy
```
Now I want to run matomo on a virtual host, my docker-compose.yml is like this:
```
version: '2'

services:
  application:
    image: 'bitnami/matomo:latest'
    expose:
      - 9000
    volumes:
      - ./config:/bitnami
    environment:
      - MARIADB_HOST=<db-host>
      - MARIADB_PORT_NUMBER=3306
      - MATOMO_DATABASE_USER=<user>
      - MATOMO_DATABASE_PASSWORD=<password>
      - MATOMO_DATABASE_NAME=<db_name>
      - VIRTUAL_HOST=matomo.local
```
But this fails during installation:
```
application_1  | Welcome to the Bitnami matomo container
application_1  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-matomo
application_1  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-matomo/issues
application_1  | 
application_1  | nami    INFO  Initializing matomo
application_1  | matomo  INFO  Preparing PHP environment...
application_1  | matomo  INFO  Preparing matomo environment...
application_1  | mysql-c INFO  Trying to connect to MySQL server
application_1  | mysql-c INFO  Found MySQL server listening at <db-host>:3306
application_1  | mysql-c INFO  MySQL server listening and working at <db-host>:3306
application_1  | matomo  INFO  Installing matomo. It could take some minutes...
application_1  | Error executing 'postInstallation': Server returned status code 500 from http://127.0.0.1/
application_1  | Server returned status code 500 from http://127.0.0.1/
test_application_1 exited with code 1
```

Is it possible to use with [nginx-proxy](https://github.com/jwilder/nginx-proxy) ?

- Output of `docker version`:

```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:13:02 2018
 OS/Arch:      darwin/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:22:38 2018
  OS/Arch:      linux/amd64
  Experimental: true
```

- Output of `docker info`:

```
Containers: 24
 Running: 1
 Paused: 0
 Stopped: 23
Images: 59
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.87-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: HGQ2:W7OE:CXE3:J6QA:SPUJ:H4DO:AQ7T:LZ5T:UJIX:GNTJ:DRAJ:GD6V
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 33
 Goroutines: 67
 System Time: 2018-05-28T15:04:07.1831767Z
 EventsListeners: 3
HTTP Proxy: docker.for.mac.http.internal:3128
HTTPS Proxy: docker.for.mac.http.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.21.1, build 5a3f1a3
docker-py version: 3.3.0
CPython version: 3.6.4
OpenSSL version: OpenSSL 1.0.2o  27 Mar 2018
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by welkie** [comment] 2018-05-28 22:43
Commenting so it's in my watchlist.
I was in this same scenario not too long ago. I wanted to put Matomo behind my existing NGINX proxy (alongside my Ghost blog). I had some issues related to using it as a subdirectory FYI. I ended up reading that with virtually every service out there, it's easier to put it behind NGINX as a subdomain. Mind if I see your NGINX conf? And have you considered not using nginx-proxy, and just using a raw NGINX container?

**Comment by mebibou** [comment] 2018-05-29 07:37
@welkie thanks for your help
My nginx.conf looks like this:
```
user www-data;

events {
  worker_connections 768;
}

http {
  upstream backend {
    server app:9000;
  }

  include /etc/nginx/mime.types;
  default_type application/octet-stream;
  gzip on;
  gzip_disable "msie6";

  server {
    listen 80;

    root /var/www/html/;
    index index.php index.html index.htm;

    location / {
      try_files $uri $uri/ =404;
    }

    error_page 404 /404.html;
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
      root /usr/share/nginx/html;
    }

    location = /favicon.ico {
      log_not_found off;
      access_log off;
    }

    location ~ \.php$ {
      fastcgi_param  GATEWAY_INTERFACE  CGI/1.1;
      fastcgi_param  SERVER_SOFTWARE    nginx;
      fastcgi_param  QUERY_STRING       $query_string;
      fastcgi_param  REQUEST_METHOD     $request_method;
      fastcgi_param  CONTENT_TYPE       $content_type;
      fastcgi_param  CONTENT_LENGTH     $content_length;
      fastcgi_param  SCRIPT_FILENAME    $document_root$fastcgi_script_name;
      fastcgi_param  SCRIPT_NAME        $fastcgi_script_name;
      fastcgi_param  REQUEST_URI        $request_uri;
      fastcgi_param  DOCUMENT_URI       $document_uri;
      fastcgi_param  DOCUMENT_ROOT      $document_root;
      fastcgi_param  SERVER_PROTOCOL    $server_protocol;
      fastcgi_param  REMOTE_ADDR        $remote_addr;
      fastcgi_param  REMOTE_PORT        $remote_port;
      fastcgi_param  SERVER_ADDR        $server_addr;
      fastcgi_param  SERVER_PORT        $server_port;
      fastcgi_param  SERVER_NAME        $server_name;
      fastcgi_intercept_errors on;
      fastcgi_pass backend;
    }
  }
}
```
I forgot where I took it though.
But I need to put this under `matomo.mydomain.com` so I'm not sure how to do this without `nginx-proxy`

**Comment by welkie** [comment] 2018-05-29 14:35
I think I see a lot in that config that isn't necessary. You shouldn't have to use any directives related to fastcgi, since the Matomo container will be able to stand on its own and handle requests. That abstraction is a benefit to using Docker. You can just have NGINX forward traffic to Matomo and forget about the details.

Here's the config I used for my blog. I removed details irrelevant to this use case like SSL and directives specific to me using it for my blog. I left what shows the proxying:

```
events {
    worker_connections  1024;
}

http {
    server {
        listen 80;

        server_name blog.mattwelke.com;        

        # Redirect everything that hits this subdomain to the Ghost blog.
        location / {
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $http_host;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_pass http://ghost:2368;
        }
    }
}
```

The `location` directive stays set to just `/` because we want to handle all traffic from the root, no subdirectory. The subdomain will vary depending on what we're hosting behind the proxy, so that allows it to identify the specific traffic. The `proxy_pass` directive takes all the traffic that hits that subdomain and forwards it to the Docker container whose host name is set to `ghost`, since that's what I chose to call it in my `docker-compose.yml` file.

**Comment by mebibou** [comment] 2018-05-29 15:57
I've tried to simplify this a bit:
```
# docker-compose.yml
version: '2'

services:
  website:
    image: 'bitnami/matomo:latest'
    expose:
      - 80
    volumes:
      - ./config:/bitnami
    environment:
      - ...

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    links:
      - website
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

# nginx.conf
server {
  listen 80 default;

  server_name _;

  location / {
    proxy_pass http://website;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
}
```
But still the same error
```
website_1  | Error executing 'postInstallation': Server returned status code 500 from http://127.0.0.1/
website_1  | Server returned status code 500 from http://127.0.0.1/
```

**Comment by juan131** [comment] 2018-05-30 08:55
Hi @mebibou 

The error you obtained is not related with your NGINX configuration. As @welkie mentioned it's related with setup scripts. 

Could you please add the environment variable below to your **docker-compose.yaml** file? It will help us to debug the reason why Matomo is unable to be installed.

```
services:
  application:
  ...
  environment:
      - NAMI_DEBUG='--log-level=trace8'
  ...
```

**Comment by vhaasteren** [comment] 2018-10-17 16:35
Has any of you ever managed to get matomo to run behind a jwilder/nginx-proxy? I'm having some difficulties with this myself (combining the jwilder nginx with a proxy-companion of jrcs/letsencrypt-nginx-proxy-companion). I have the jwilder proxy running with a bunch of wordpress sites behind it. Now I just want to add matomo on it's own subdomain.

**Comment by juan131** [comment] 2018-10-18 07:48
Hi @vhaasteren 

What difficulties did you find? Could you please provide more info about the issue you're facing with Matomo?

**Comment by vhaasteren** [comment] 2018-10-18 18:16
Sure, here's the thing. I have a jwilder/nginx-proxy running, and I want to place bitnami matomo behind it. When I run the below docker-compose just by itself (not behind the proxy) on port 8080, it works. However, when I change to behind the proxy (comment out the 'ports', and do an 'expose', as per below) ,I get a 500 bad gateway error). When I just put a simple flask app behind the nginx proxy with the same matomo subdomain, it works, so I figure it is not an issue with my jwilder/nginx-proxy setup.

Am I missing something on how to set up matomo behind the proxy? Thanks!

docker-compose.yml:

version: '2'

services:

  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - MARIADB_USER=bn_matomo
      - MARIADB_PASSWORD=bitnami_password
      - MARIADB_DATABASE=bitnami_matomo
      - MARIADB_ROOT_PASSWORD=root_password
    volumes:
      - 'mariadb_data:/bitnami'

  matomo:
    image: 'bitnami/matomo:latest'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MATOMO_HOST=127.0.0.1
      - MATOMO_USERNAME=matomo
      - MATOMO_PASSWORD=bitnami_password
      - MATOMO_DATABASE_USER=bn_matomo
      - MATOMO_DATABASE_PASSWORD=bitnami_password
      - MATOMO_DATABASE_NAME=bitnami_matomo
      - ALLOW_EMPTY_PASSWORD=no
      - VIRTUAL_HOST=matomo.somedomain.com
      - LETSENCRYPT_HOST=matomo.somedomain.com
      - LETSENCRYPT_EMAIL=email@somedomain.com
    labels:
      kompose.service.type: nodeport
    #ports:
    #  - '8080:80'
    #  - '443:443'
    expose:
      - 80
      - 443
    depends_on:
      - mariadb
    volumes:
      - 'matomo_data:/bitnami'


volumes:

  mariadb_data:
    driver: local

  matomo_data:
    driver: local

**Comment by juan131** [comment] 2018-10-22 12:47
Hi @vhaasteren 

Could you share the configuration used on your NGINX proxy `jwilder/nginx-proxy`??? I just want to replicate the whole scenario to understand what's going on

Did you find similar issues using other proxy solutions?

**Comment by vhaasteren** [comment] 2018-10-22 16:33
Ok, the docker-compose file is pasted below. Pretty standard I think. And I indeed just tried traefik as a reverse proxy, which requires a bit more setup, but matomo works properly with that. Perhaps it is my nginx config, and not bitnami/matomo...  but I have no clue what is up with nginx. Anyway, since traefik just works, consider this low priority.

I have also added a file 'comainname.xxx' in vhost.d, with content "server_tokens off;".

docker-compose.yml:
proxy:
  image: jwilder/nginx-proxy:latest
  restart: always
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - ./vhost.d:/etc/nginx/vhost.d
    - ./conf.d:/etc/nginx/conf.d
    - ./certs:/etc/nginx/certs:ro
    - /usr/share/nginx/html
proxy-companion:
  image: jrcs/letsencrypt-nginx-proxy-companion
  restart: always
  volumes:
    - ./certs:/etc/nginx/certs:rw
    - /var/run/docker.sock:/var/run/docker.sock:ro
  volumes_from:
    - proxy

**Comment by juan131** [comment] 2018-10-23 07:40
Hi @vhaasteren 

> And I indeed just tried traefik as a reverse proxy, which requires a bit more setup, but matomo works properly with that.

Great! At least you have a workaround and it's very likely to be related with the NGINX configuration.

You're mounting a lot of NGINX configuration files on the `jwilder/nginx-proxy` container. I can't reproduce the scenario unless you shared with me whatever you mounting there (do not share with me the certificates):

```
  volumes:
    ...
    - ./vhost.d:/etc/nginx/vhost.d
    - ./conf.d:/etc/nginx/conf.d
    ...
```

**Comment by vhaasteren** [comment] 2018-11-02 04:56
Well, the conf.d, html, and vhost.d mounts can be deleted from the docker-compose.yml file. They were emty mounts for this example. Apologies for leaving them in. Results are the same for me without those in there. As far as I understand, my nginx setup is very vanilla.

Regardless, I've been very happy running under traefik for the past week and a half or so.

**Comment by juan131** [comment] 2018-11-02 08:50
Hi @vhaasteren 

> I've been very happy running under traefik for the past week and a half or so.

I'd close this issue if you found an alternative that's not giving you issues to proxy-redirect traffic to your Matomo container. Please feel free to reopen it if you consider we should continue discussing about it.

**Closed by juan131** 2018-11-02 08:50 UTC

**Comment by juan131** [comment] 2018-11-26 09:01
Hi @RobertLos 

Please correct me if I'm wrong but your issue is related to the "source ip" registered in the Apache logs. I mean, the Apache running on Matomo container. That's an issue on your NGINX configuration since it's not preserving the original IP when doing the redirection.

The custom header to use to do so is the one below:
```
   proxy_set_header X-Real-IP $remote_addr;
```

According to [this blog](https://calvin.me/forward-ip-addresses-when-using-nginx-proxy) you should also ensure that you set the header `proxy_set_header X-Forwarded-For` to `$remote_addr;`:

```
   proxy_set_header X-Forwarded-For $remote_addr;
```

Sorry but I'm not an expert on NGINX configuration. You might get more information on NGINX forums.
